# Generated by Django 6.0.5 on 2026-06-22 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(max_length=80, unique=True, verbose_name="Klucz"),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("home", "Strona główna"),
                            ("about", "O nas"),
                            ("global", "Globalne"),
                        ],
                        max_length=20,
                        verbose_name="Grupa",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=200, verbose_name="Etykieta w CMS"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Tytuł"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Podtytuł"
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="Treść")),
                (
                    "body_extra",
                    models.TextField(blank=True, verbose_name="Treść dodatkowa"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="cms/pages/", verbose_name="Obraz"
                    ),
                ),
                (
                    "button_label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Etykieta przycisku"
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="URL przycisku"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Blok treści",
                "verbose_name_plural": "Bloki treści",
                "ordering": ["group", "label"],
            },
        ),
        migrations.CreateModel(
            name="DownloadCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="Slug"),
                ),
                ("label", models.CharField(max_length=200, verbose_name="Nazwa")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
            ],
            options={
                "verbose_name": "Kategoria plików",
                "verbose_name_plural": "Kategorie plików",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tytuł")),
                ("lead", models.TextField(blank=True, verbose_name="Lead")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="cms/hero/", verbose_name="Obraz"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Slajd hero",
                "verbose_name_plural": "Slajdy hero",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Stanowisko")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Lokalizacja"
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Typ zatrudnienia"
                    ),
                ),
                ("excerpt", models.TextField(blank=True, verbose_name="Zajawka")),
                ("body", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywna"),
                ),
            ],
            options={
                "verbose_name": "Oferta pracy",
                "verbose_name_plural": "Oferty pracy",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tytuł")),
                ("excerpt", models.TextField(blank=True, verbose_name="Zajawka")),
                ("body", models.TextField(blank=True, verbose_name="Treść")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="cms/articles/", verbose_name="Obraz"
                    ),
                ),
                ("published_at", models.DateField(verbose_name="Data publikacji")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Opublikowany"),
                ),
            ],
            options={
                "verbose_name": "Aktualność",
                "verbose_name_plural": "Aktualności",
                "ordering": ["-published_at", "title"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, verbose_name="Slug")),
                ("title", models.CharField(max_length=200, verbose_name="Nazwa")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Podtytuł"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "description_extra",
                    models.TextField(blank=True, verbose_name="Opis dodatkowy"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="cms/products/",
                        verbose_name="Obraz główny",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Produkt",
                "verbose_name_plural": "Produkty",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="Slug"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Nazwa")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="cms/products/groups/",
                        verbose_name="Obraz",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Grupa produktów",
                "verbose_name_plural": "Grupy produktów",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField(verbose_name="Cytat")),
                ("author", models.CharField(max_length=200, verbose_name="Autor")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Opinia",
                "verbose_name_plural": "Opinie",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=64, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "infoline",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Infolinia"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adres")),
                (
                    "footer_tagline",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tagline stopki"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ustawienia strony",
                "verbose_name_plural": "Ustawienia strony",
            },
        ),
        migrations.CreateModel(
            name="SurfaceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Nazwa")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="cms/surfaces/", verbose_name="Obraz"
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=120, verbose_name="Kolor"),
                ),
                (
                    "surface",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Powierzchnia"
                    ),
                ),
                (
                    "format_size",
                    models.CharField(blank=True, max_length=120, verbose_name="Format"),
                ),
                (
                    "thickness",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Grubość"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Barwa / powierzchnia",
                "verbose_name_plural": "Barwy i powierzchnie",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tytuł")),
                ("excerpt", models.TextField(blank=True, verbose_name="Zajawka")),
                ("body", models.TextField(blank=True, verbose_name="Treść")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="cms/articles/", verbose_name="Obraz"
                    ),
                ),
                ("published_at", models.DateField(verbose_name="Data publikacji")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Opublikowany"),
                ),
            ],
            options={
                "verbose_name": "Porada",
                "verbose_name_plural": "Porady",
                "ordering": ["-published_at", "title"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DownloadItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tytuł")),
                (
                    "file",
                    models.FileField(upload_to="cms/downloads/", verbose_name="Plik"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("zip", "ZIP")],
                        default="pdf",
                        max_length=8,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Opublikowany"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cms.downloadcategory",
                        verbose_name="Kategoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plik do pobrania",
                "verbose_name_plural": "Pliki do pobrania",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ProductGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="cms/products/gallery/",
                        verbose_name="Obraz",
                    ),
                ),
                (
                    "alt",
                    models.CharField(blank=True, max_length=255, verbose_name="Alt"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="cms.product",
                        verbose_name="Produkt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zdjęcie galerii",
                "verbose_name_plural": "Zdjęcia galerii",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="cms.productgroup",
                verbose_name="Grupa",
            ),
        ),
        migrations.CreateModel(
            name="ProductPin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        max_digits=5,
                        verbose_name="Pozycja X (%)",
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        max_digits=5,
                        verbose_name="Pozycja Y (%)",
                    ),
                ),
                ("text", models.TextField(verbose_name="Treść tooltipa")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="cms.product",
                        verbose_name="Produkt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pin na zdjęciu",
                "verbose_name_plural": "Piny na zdjęciu",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120, verbose_name="Etykieta")),
                ("value", models.CharField(max_length=200, verbose_name="Wartość")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="cms.product",
                        verbose_name="Produkt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parametr produktu",
                "verbose_name_plural": "Parametry produktu",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("group", "slug")},
        ),
    ]
