# Generated by Django 6.0.5 on 2026-06-24 12:09

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


FILTER_ATTRIBUTE_NAMES = {
    "format",
    "grubosc",
    "kolor",
    "powierzchnia",
    "grubość",
}


def migrate_specs_to_attributes(apps, schema_editor):
    ProductSpec = apps.get_model("cms", "ProductSpec")
    ProductAttribute = apps.get_model("cms", "ProductAttribute")
    ProductAttributeOption = apps.get_model("cms", "ProductAttributeOption")
    ProductAttributeAssignment = apps.get_model("cms", "ProductAttributeAssignment")

    attribute_cache = {}

    for spec in ProductSpec.objects.select_related("product").order_by("sort_order", "id"):
        label = (spec.label or "").strip()
        value = (spec.value or "").strip()
        if not label or not value:
            continue

        slug = slugify(label) or f"attr-{spec.pk}"
        if slug not in attribute_cache:
            attribute, _ = ProductAttribute.objects.get_or_create(
                slug=slug,
                defaults={
                    "name": label,
                    "show_in_filters": slug in FILTER_ATTRIBUTE_NAMES
                    or slugify(label) in FILTER_ATTRIBUTE_NAMES,
                    "sort_order": spec.sort_order,
                },
            )
            attribute_cache[slug] = attribute
        attribute = attribute_cache[slug]

        option, _ = ProductAttributeOption.objects.get_or_create(
            attribute=attribute,
            value=value,
            defaults={"sort_order": 0},
        )
        ProductAttributeAssignment.objects.get_or_create(
            product=spec.product,
            option=option,
            defaults={"sort_order": spec.sort_order},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nazwa")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                (
                    "show_in_filters",
                    models.BooleanField(
                        default=False, verbose_name="W filtrach na stronie"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
            ],
            options={
                "verbose_name": "Atrybut produktu",
                "verbose_name_plural": "Atrybuty produktów",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200, verbose_name="Wartość")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="cms.productattribute",
                        verbose_name="Atrybut",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wartość atrybutu",
                "verbose_name_plural": "Wartości atrybutów",
                "ordering": ["sort_order", "value"],
                "unique_together": {("attribute", "value")},
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_assignments",
                        to="cms.product",
                        verbose_name="Produkt",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="cms.productattributeoption",
                        verbose_name="Wartość",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atrybut produktu",
                "verbose_name_plural": "Atrybuty produktu",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.RunPython(migrate_specs_to_attributes, migrations.RunPython.noop),
    ]
