# Generated by Django 5.2.14 on 2026-07-16 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_product_attributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="FloatingPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("modal", "Okno dialogowe"),
                            ("side", "Widget boczny"),
                        ],
                        max_length=10,
                        verbose_name="Położenie",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="cms/promotions/", verbose_name="Zdjęcie"
                    ),
                ),
                ("link_url", models.CharField(max_length=500, verbose_name="Link")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Widget promocyjny",
                "verbose_name_plural": "Widgety promocyjne",
                "ordering": ["placement", "id"],
            },
        ),
        migrations.CreateModel(
            name="FormWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="Nazwa widgetu"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tytuł")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="cms/forms/", verbose_name="Zdjęcie"
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        max_length=254, verbose_name="Adres e-mail odbiorcy"
                    ),
                ),
                (
                    "required_fields_text",
                    models.TextField(blank=True, verbose_name="Opis pól obowiązkowych"),
                ),
                (
                    "consent_text",
                    models.TextField(verbose_name="Zgoda na przetwarzanie danych"),
                ),
                (
                    "thanks_image",
                    models.ImageField(
                        blank=True,
                        upload_to="cms/forms/thanks/",
                        verbose_name="Grafika podziękowania",
                    ),
                ),
                (
                    "thanks_text",
                    models.TextField(blank=True, verbose_name="Tekst podziękowania"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Widget formularza",
                "verbose_name_plural": "Widgety formularzy",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PromotionSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Treść")),
                (
                    "link_label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Etykieta linku"
                    ),
                ),
                (
                    "link_url",
                    models.CharField(blank=True, max_length=500, verbose_name="Link"),
                ),
                (
                    "active_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aktywny od"
                    ),
                ),
                (
                    "active_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aktywny do"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Slajd paska promocyjnego",
                "verbose_name_plural": "Slajdy paska promocyjnego",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SalesPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nazwa")),
                ("address", models.CharField(max_length=300, verbose_name="Adres")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=80, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, verbose_name="Link do strony"),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("full", "Pełna oferta"),
                            ("musso", "Płyty dekoracyjne MUSSO"),
                        ],
                        default="full",
                        max_length=10,
                        verbose_name="Oferta",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Punkt sprzedaży",
                "verbose_name_plural": "Punkty sprzedaży",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="heroslide",
            name="button_label",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Etykieta przycisku"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="button_url",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Link przycisku"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="media_type",
            field=models.CharField(
                choices=[("image", "Zdjęcie"), ("video", "Film")],
                default="image",
                max_length=10,
                verbose_name="Typ medium",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="mobile_image",
            field=models.ImageField(
                blank=True, upload_to="cms/hero/mobile/", verbose_name="Obraz mobile"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="video",
            field=models.FileField(
                blank=True, upload_to="cms/hero/video/", verbose_name="Film"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="video_url",
            field=models.URLField(blank=True, verbose_name="Link do filmu"),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="cms/hero/", verbose_name="Obraz desktop"
            ),
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=120, verbose_name="Imię")),
                (
                    "last_name",
                    models.CharField(max_length=120, verbose_name="Nazwisko"),
                ),
                ("street", models.CharField(max_length=200, verbose_name="Ulica")),
                (
                    "house_number",
                    models.CharField(max_length=40, verbose_name="Nr domu/mieszkania"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Kod pocztowy"),
                ),
                ("city", models.CharField(max_length=150, verbose_name="Miejscowość")),
                (
                    "company",
                    models.CharField(blank=True, max_length=200, verbose_name="Firma"),
                ),
                ("consent", models.BooleanField(default=False, verbose_name="Zgoda")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data zgłoszenia"
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="cms.formwidget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zgłoszenie formularza",
                "verbose_name_plural": "Zgłoszenia formularzy",
                "ordering": ["-created_at"],
            },
        ),
    ]
