# Generated by Django 5.2.14 on 2026-07-16 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_contact_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurfaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Nazwa")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        upload_to="cms/surfaces/icons/",
                        verbose_name="Ikona",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Opis powierzchni"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Rodzaj powierzchni",
                "verbose_name_plural": "Rodzaje powierzchni",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="packshot_image",
            field=models.ImageField(
                blank=True,
                upload_to="cms/products/packshots/",
                verbose_name="Zdjęcie Packshot",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_to_products",
                to="cms.product",
                verbose_name="Polecane produkty",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="show_main_image",
            field=models.BooleanField(
                default=True, verbose_name="Pokaż zdjęcie główne z pinami"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="show_packshot",
            field=models.BooleanField(
                default=False, verbose_name="Pokaż sekcję Packshot"
            ),
        ),
        migrations.AddField(
            model_name="productpin",
            name="gallery_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pins",
                to="cms.productgalleryimage",
                verbose_name="Zdjęcie galerii",
            ),
        ),
        migrations.AddField(
            model_name="surfaceitem",
            name="application",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Zastosowanie"
            ),
        ),
        migrations.AddField(
            model_name="surfaceitem",
            name="load_capacity",
            field=models.CharField(blank=True, max_length=120, verbose_name="Nośność"),
        ),
        migrations.AddField(
            model_name="surfaceitem",
            name="product_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paving", "Kostka brukowa"),
                    ("slab", "Płyta dekoracyjna"),
                    ("small_arch", "Mała architektura"),
                    ("sand", "Piasek fugowy"),
                ],
                max_length=20,
                verbose_name="Rodzaj produktu",
            ),
        ),
        migrations.CreateModel(
            name="SurfaceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Nazwa")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywna"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.surfacecategory",
                        verbose_name="Sekcja nadrzędna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoria barw i powierzchni",
                "verbose_name_plural": "Kategorie barw i powierzchni",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="surfaceitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="cms.surfacecategory",
                verbose_name="Kategoria",
            ),
        ),
        migrations.AddField(
            model_name="surfaceitem",
            name="surface_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="cms.surfacetype",
                verbose_name="Rodzaj powierzchni",
            ),
        ),
    ]
