# Generated by Django 5.2.14 on 2026-07-16 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_surface_defaults_and_products_cta"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tytuł")),
                ("body", models.TextField(blank=True, verbose_name="Treść")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokumenty",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="downloaditem",
            name="file_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Numer pliku"
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="cms/jobs/", verbose_name="Zdjęcie"
            ),
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Imię i nazwisko"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("phone", models.CharField(max_length=80, verbose_name="Telefon")),
                (
                    "cv",
                    models.FileField(
                        upload_to="cms/jobs/applications/", verbose_name="CV"
                    ),
                ),
                ("consent", models.BooleanField(default=False, verbose_name="Zgoda")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data zgłoszenia"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="cms.jobopening",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aplikacja",
                "verbose_name_plural": "Aplikacje",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="cms/articles/gallery/", verbose_name="Zdjęcie"
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Opis zdjęcia"
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("full", "Pełna szerokość"),
                            ("half", "1/2 szerokości"),
                            ("third", "1/3 szerokości"),
                        ],
                        default="full",
                        max_length=10,
                        verbose_name="Układ",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="cms.newspost",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="cms/articles/gallery/", verbose_name="Zdjęcie"
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Opis zdjęcia"
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("full", "Pełna szerokość"),
                            ("half", "1/2 szerokości"),
                            ("third", "1/3 szerokości"),
                        ],
                        default="full",
                        max_length=10,
                        verbose_name="Układ",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="cms.tip",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
    ]
