# Generated by Django 5.2.14 on 2026-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0009_default_legal_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standardowa karta"),
                    ("descriptive", "Karta opisowa"),
                ],
                default="standard",
                max_length=20,
                verbose_name="Typ karty",
            ),
        ),
        migrations.AddField(
            model_name="productgalleryimage",
            name="pins_enabled",
            field=models.BooleanField(default=False, verbose_name="Aktywuj piny"),
        ),
    ]
