# Generated by Django 5.2.14 on 2026-09-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0013_product_tech_packs"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspost",
            name="legacy_slugs",
            field=models.TextField(
                blank=True,
                help_text="Wewnętrzna lista starych adresów (po jednym w linii) do przekierowań.",
                verbose_name="Poprzednie adresy",
            ),
        ),
        migrations.AddField(
            model_name="tip",
            name="legacy_slugs",
            field=models.TextField(
                blank=True,
                help_text="Wewnętrzna lista starych adresów (po jednym w linii) do przekierowań.",
                verbose_name="Poprzednie adresy",
            ),
        ),
    ]
