# Generated by Django 5.2.14 on 2026-09-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0014_article_legacy_slugs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salespoint",
            options={
                "ordering": ["sort_name", "name"],
                "verbose_name": "Punkt sprzedaży",
                "verbose_name_plural": "Punkty sprzedaży",
            },
        ),
        migrations.AddField(
            model_name="salespoint",
            name="city",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Miejscowość"
            ),
        ),
        migrations.AddField(
            model_name="salespoint",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Np. 51.436519. Używana do mapy i przycisku „Wyznacz trasę”.",
                max_digits=9,
                null=True,
                verbose_name="Szerokość geograficzna",
            ),
        ),
        migrations.AddField(
            model_name="salespoint",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Np. 19.225727.",
                max_digits=9,
                null=True,
                verbose_name="Długość geograficzna",
            ),
        ),
        migrations.AddField(
            model_name="salespoint",
            name="sort_name",
            field=models.CharField(
                blank=True,
                help_text="Używana do sortowania A–Z. Wpisz nazwę bez PPHU, PHU itd.",
                max_length=200,
                verbose_name="Nazwa do sortowania",
            ),
        ),
        migrations.AddField(
            model_name="salespoint",
            name="voivodeship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dolnoslaskie", "dolnośląskie"),
                    ("kujawsko-pomorskie", "kujawsko-pomorskie"),
                    ("lubelskie", "lubelskie"),
                    ("lubuskie", "lubuskie"),
                    ("lodzkie", "łódzkie"),
                    ("malopolskie", "małopolskie"),
                    ("mazowieckie", "mazowieckie"),
                    ("opolskie", "opolskie"),
                    ("podkarpackie", "podkarpackie"),
                    ("podlaskie", "podlaskie"),
                    ("pomorskie", "pomorskie"),
                    ("slaskie", "śląskie"),
                    ("swietokrzyskie", "świętokrzyskie"),
                    ("warminsko-mazurskie", "warmińsko-mazurskie"),
                    ("wielkopolskie", "wielkopolskie"),
                    ("zachodniopomorskie", "zachodniopomorskie"),
                ],
                max_length=40,
                verbose_name="Województwo",
            ),
        ),
        migrations.AlterField(
            model_name="salespoint",
            name="website_url",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Adres strony"
            ),
        ),
    ]
