# Generated by Django 5.2.14 on 2026-09-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0015_salespoint_locator_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="commercial_label",
            field=models.CharField(
                blank=True,
                default="Dział handlowy i księgowy",
                max_length=120,
                verbose_name="Dział w stopce",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="commercial_phone",
            field=models.CharField(
                blank=True,
                default="+48 755 54 40",
                max_length=64,
                verbose_name="Telefon działu handlowego",
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Tytuł"),
        ),
        migrations.AlterField(
            model_name="promotionslide",
            name="text",
            field=models.TextField(blank=True, verbose_name="Treść"),
        ),
    ]
