# Generated by Django 6.0.5 on 2026-09-30 09:08

import django.db.models.deletion
from django.db import migrations, models


def _copy_related_products(apps, schema_editor):
    related = apps.get_model("cms", "ProductRelatedProduct")
    connection = schema_editor.connection
    table_names = connection.introspection.table_names()
    legacy = "cms_product_related_products"
    if legacy not in table_names:
        return
    with connection.cursor() as cursor:
        cursor.execute(f"SELECT * FROM {legacy} LIMIT 0")
        columns = [col[0] for col in cursor.description]
        cursor.execute(f"SELECT * FROM {legacy}")
        rows = cursor.fetchall()
    from_key = next((c for c in columns if c.endswith("from_product_id")), None)
    to_key = next((c for c in columns if c.endswith("to_product_id")), None)
    if not from_key or not to_key:
        from_key = next((c for c in columns if "from" in c and c.endswith("_id")), None)
        to_key = next((c for c in columns if "to" in c and c.endswith("_id")), None)
    if not from_key or not to_key:
        return
    for index, row in enumerate(rows):
        data = dict(zip(columns, row))
        related.objects.get_or_create(
            from_product_id=data[from_key],
            to_product_id=data[to_key],
            defaults={"sort_order": index},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0019_floatingpromotion_seen_reset_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentblock",
            options={
                "ordering": ["group", "sort_order", "label"],
                "verbose_name": "Blok treści",
                "verbose_name_plural": "Bloki treści",
            },
        ),
        migrations.AlterModelOptions(
            name="jobopening",
            options={
                "ordering": ["sort_order", "title"],
                "verbose_name": "Oferta pracy",
                "verbose_name_plural": "Oferty pracy",
            },
        ),
        migrations.AddField(
            model_name="contentblock",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="application_email",
            field=models.EmailField(
                blank=True,
                help_text="Na ten adres trafiają aplikacje. Puste = adres z ustawień strony.",
                max_length=254,
                verbose_name="E-mail na CV",
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
        ),
        migrations.AddField(
            model_name="product",
            name="related_tips",
            field=models.ManyToManyField(
                blank=True,
                related_name="featured_on_products",
                to="cms.tip",
                verbose_name="Porady na karcie produktu",
            ),
        ),
        migrations.AddField(
            model_name="productattributeoption",
            name="icon_display",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Tekst / brak"),
                    ("pedestrian", "Ruch pieszy"),
                    ("car", "Ruch pojazdów"),
                    ("pedestrian_car", "Pieszy i pojazdy"),
                ],
                max_length=20,
                verbose_name="Ikona nośności",
            ),
        ),
        migrations.AddField(
            model_name="surfaceitem",
            name="filter_application",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Filtr: zastosowanie"
            ),
        ),
        migrations.AddField(
            model_name="surfaceitem",
            name="filter_category",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Filtr: kategoria"
            ),
        ),
        migrations.AddField(
            model_name="surfaceitem",
            name="filter_color",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Filtr: kolor"
            ),
        ),
        migrations.AddField(
            model_name="surfaceitem",
            name="filter_format",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Filtr: format"
            ),
        ),
        migrations.AddField(
            model_name="surfaceitem",
            name="filter_load",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Filtr: nośność"
            ),
        ),
        migrations.AddField(
            model_name="surfaceitem",
            name="filter_product_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Filtr: nazwa produktu"
            ),
        ),
        migrations.AddField(
            model_name="surfaceitem",
            name="filter_surface",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Filtr: powierzchnia"
            ),
        ),
        migrations.AddField(
            model_name="surfaceitem",
            name="filter_thickness",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Filtr: grubość"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="cms.productgroup",
                verbose_name="Kategoria",
            ),
        ),
        migrations.AlterField(
            model_name="productattributeoption",
            name="value",
            field=models.TextField(blank=True, verbose_name="Wartość"),
        ),
        migrations.AlterField(
            model_name="productcolorimage",
            name="caption",
            field=models.TextField(blank=True, verbose_name="Nazwa koloru"),
        ),
        migrations.AlterField(
            model_name="productpackshotimage",
            name="caption",
            field=models.TextField(blank=True, verbose_name="Podpis"),
        ),
        migrations.AlterField(
            model_name="producttechrow",
            name="icon_preset",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Brak"),
                    ("load", "Nośność (legacy)"),
                    ("pedestrian", "Ruch pieszy"),
                    ("car", "Ruch pojazdów"),
                    ("pedestrian_car", "Pieszy i pojazdy"),
                ],
                max_length=20,
                verbose_name="Ikona",
            ),
        ),
        migrations.AlterField(
            model_name="salespoint",
            name="email",
            field=models.TextField(
                blank=True,
                help_text="Jeden adres lub kilka oddzielonych przecinkiem, średnikiem lub nową linią.",
                verbose_name="E-mail",
            ),
        ),
        migrations.CreateModel(
            name="ProductRelatedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "from_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_product_links",
                        to="cms.product",
                        verbose_name="Produkt",
                    ),
                ),
                (
                    "to_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_from_links",
                        to="cms.product",
                        verbose_name="Polecany produkt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Powiązanie produktów",
                "verbose_name_plural": "Powiązania produktów",
                "ordering": ["sort_order", "id"],
                "unique_together": {("from_product", "to_product")},
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _copy_related_products(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="product",
            name="related_products",
        ),
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_to_products",
                through="cms.ProductRelatedProduct",
                to="cms.product",
                verbose_name="Polecane produkty",
            ),
        ),
    ]
